### PR TITLE
add cpp-ethereum (for solc and lllc) and serpent installs to Dockerfile

### PR DESCRIPTION
**Pull request by ebuchman**

### CODE REVIEW

**Comment by compleatang** [comment]
I've cleaned the docker file a bit to harmonize it with prior work. This should be good to merge from my side. Note https://github.com/eris-ltd/builder/pull/15 will make the Dockerfile in this repository canonical.

**Comment by ebuchman** [comment]
I have a number of issues with the latest commit:

1) Golang should be the first thing we install so the dockerfile is most like a golang image and so if we change something in the ethereum install (likely) we don't have to wait for the golang to be reinstalled. It would be nice if we could just start with the official golang image but its debian based and who knows how to build ethereum on anything other than ubuntu. Is there something wrong with this thinking?

2) I prefer the apt-get installs to be spread out over multiple commands rather than one for sake of readability. Not the biggest deal but it bothers me.

3) Does this even work? I found `--no-install-recommends` and `rm -rf /var/lib/apt/lists/*` to be suicidal to progress. Maybe you can explain? I guess the rm is to clean up after we no longer need to apt-get install?

4) David mentioned we could shorten this line `RUN groupadd --system eris && useradd --system --create-home --gid eris eris` to this: `RUN useradd --system --create-home eris`. Is this not correct?

**Comment by compleatang** [comment]
1) No problem. That seems reasonable. 

2) The reason most docker tutorials recommend compiling these commands basically into one long run command is for caching, basically for the same reason that you noted in one. However given ethereum is in rapid develop, probably we should carve out the eth commands so that the rest can stay cached.

**Comment by compleatang** [comment]
3) no install recommends should just squash the notification of recommended packages and the rm there just is trimming up the old dpkg lists.

**Comment by compleatang** [comment]
4) We use both the group and the user in the rest of the containers but as David said we should be able to get away without the eris group.

**Comment by ebuchman** [comment]
How do we use the group? I'll make the other changes and push again

**Comment by compleatang** [comment]
I don't think we use the group. 

```
     --no-install-recommends
           Do not consider recommended packages as a dependency for
           installing. Configuration Item: APT::Install-Recommends.
```

via http://manpages.ubuntu.com/manpages/utopic/man8/apt-get.8.html

**Comment by ebuchman** [comment]
are we sure we don't want the recommended packages? Isn't there some adage that goes "anything that can go wrong with a cpp software installation will go wrong?"

**Pull request merged**
